# Generated by Django 6.0 on 2025-12-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingroom',
            options={'verbose_name': '会议室'},
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='area',
            field=models.FloatField(default=0.0, verbose_name='面积'),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='photo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='图片URL'),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='usage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='用途'),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='容纳人数'),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='是否可预约'),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='room_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='房号'),
        ),
        migrations.AlterModelTable(
            name='meetingroom',
            table='meeting_room',
        ),
    ]
