# Generated by Django 6.0 on 2025-12-14 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_alter_meetingroom_options_meetingroom_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='预约日期')),
                ('start_hour', models.IntegerField(verbose_name='开始时间(小时)')),
                ('end_hour', models.IntegerField(verbose_name='结束时间(小时)')),
                ('topic', models.CharField(blank=True, max_length=255, null=True, verbose_name='会议主题')),
                ('status', models.CharField(choices=[('PENDING', '审核中'), ('APPROVED', '已通过'), ('REJECTED', '已驳回'), ('CANCELED', '已取消'), ('USED', '已使用')], default='PENDING', max_length=20, verbose_name='状态')),
                ('reject_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='驳回原因')),
                ('approve_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.meetingroom', verbose_name='会议室')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='预约人')),
            ],
            options={
                'verbose_name': '预约记录',
                'db_table': 'reservation',
            },
        ),
    ]
